server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///Users/oleksandr/cloud-project/new-version/spring-cloud-study/servercfn/src/main/resources/config/licensingservice